name: Deploy

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build and Deploy
        run: |
          npm run build
          git config user.email "yakuzawot6@gmail.com"
          git config user.name "@Gary-Ihar"
          npm run deploy
